semi: true # 文末のセミコロンを強制する
printWidth: 100 # 行の文字数を"100"文字に制限
tabWidth: 4 # インデント幅をスペース"2"個
singleQuote: true # 文字列リテラルのシングルクォーテーションとする
quoteProps: as-needed # オブジェクトリテラルのプロパティ名のクォーテーションは"必要なときのみ"とする
jsxSingleQuote: false # JSX のプロパティの値は、ダブルクォーテーションとする
trailingComma: all # オブジェクトリテラルなどの最後のカンマを強制する
bracketSpacing: true # {}のカッコに隣接するスペースをいれる
jsxBracketSameLine: false # JSXの後ろの'>'を同じ行にする
arrowParens: avoid # Arrow関数の引数のカッコは必要な場合のみつける
endOfLine: lf # 改行コードを "lf" にする